import type {
  User, UserStats, Question, Exam, TestResult,
  PerformanceData, TopicHeatmapData, LeaderboardEntry,
  DiscussionThread, StudyRoom, DailyTask, Badge
} from '@/types';

export const mockUser: User = {
  id: 'u1',
  name: 'Rahul Sharma',
  email: 'rahul@example.com',
  phone: '+91 9876543210',
  role: 'student',
  tier: 'pro',
  examPreferences: ['SSC', 'Banking'],
  xp: 4250,
  streak: 12,
  createdAt: '2024-01-15',
};

export const mockUserStats: UserStats = {
  totalQuestionsSolved: 2847,
  totalTestsTaken: 34,
  totalStudyHours: 156,
  averageAccuracy: 72.4,
  currentStreak: 12,
  longestStreak: 21,
  rank: 342,
  percentile: 88.5,
  weeklyXP: 680,
};

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    text: 'If the ratio of ages of A and B is 3:5, and the sum of their ages is 48, what is the age of B?',
    options: [
      { id: 'a', text: '18 years' },
      { id: 'b', text: '30 years' },
      { id: 'c', text: '24 years' },
      { id: 'd', text: '20 years' },
    ],
    correctOptionId: 'b',
    explanation: 'Let A = 3x and B = 5x. Then 3x + 5x = 48 → 8x = 48 → x = 6. So B = 5×6 = 30.',
    subject: 'Quantitative Aptitude',
    topic: 'Ratio & Proportion',
    subtopic: 'Age Problems',
    difficulty: 'Easy',
    examCategory: ['SSC', 'Banking'],
    isPYQ: true,
    pyqYear: 2023,
    isBookmarked: false,
    tags: ['ratio', 'age'],
  },
  {
    id: 'q2',
    text: 'A train travelling at 72 km/h crosses a pole in 20 seconds. What is the length of the train?',
    options: [
      { id: 'a', text: '360 m' },
      { id: 'b', text: '400 m' },
      { id: 'c', text: '300 m' },
      { id: 'd', text: '320 m' },
    ],
    correctOptionId: 'b',
    explanation: 'Speed = 72 km/h = 72 × (5/18) = 20 m/s. Length = Speed × Time = 20 × 20 = 400 m.',
    subject: 'Quantitative Aptitude',
    topic: 'Speed, Time & Distance',
    subtopic: 'Trains',
    difficulty: 'Medium',
    examCategory: ['SSC', 'Banking', 'RRB'],
    isPYQ: true,
    pyqYear: 2022,
    isBookmarked: true,
    tags: ['trains', 'speed'],
  },
  {
    id: 'q3',
    text: 'The Parliament of India consists of which of the following?',
    options: [
      { id: 'a', text: 'Lok Sabha and Rajya Sabha' },
      { id: 'b', text: 'President, Lok Sabha and Rajya Sabha' },
      { id: 'c', text: 'President and Lok Sabha only' },
      { id: 'd', text: 'Prime Minister, Lok Sabha and Rajya Sabha' },
    ],
    correctOptionId: 'b',
    explanation: 'Article 79 of the Indian Constitution states that Parliament consists of the President and two Houses — Rajya Sabha and Lok Sabha.',
    subject: 'General Awareness',
    topic: 'Indian Polity',
    subtopic: 'Parliament',
    difficulty: 'Easy',
    examCategory: ['SSC', 'Banking', 'UPSC'],
    isPYQ: true,
    pyqYear: 2021,
    isBookmarked: false,
    tags: ['polity', 'parliament', 'constitution'],
  },
  {
    id: 'q4',
    text: 'In a certain code, MONKEY is written as XDJMNL. How is TIGER written in that code?',
    options: [
      { id: 'a', text: 'QDFHS' },
      { id: 'b', text: 'SHFPD' },
      { id: 'c', text: 'UJHFS' },
      { id: 'd', text: 'PHHQD' },
    ],
    correctOptionId: 'a',
    explanation: 'Each letter is replaced by the letter that is 1 step backward in the alphabet pattern. T→Q, I→D, G→F, E→H, R→S.',
    subject: 'Reasoning Ability',
    topic: 'Coding-Decoding',
    difficulty: 'Medium',
    examCategory: ['SSC', 'Banking'],
    isPYQ: false,
    isBookmarked: false,
    tags: ['coding', 'reasoning'],
  },
  {
    id: 'q5',
    text: 'Find the next term in the series: 2, 6, 12, 20, 30, ?',
    options: [
      { id: 'a', text: '40' },
      { id: 'b', text: '42' },
      { id: 'c', text: '38' },
      { id: 'd', text: '44' },
    ],
    correctOptionId: 'b',
    explanation: 'The series follows n(n+1) pattern: 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42.',
    subject: 'Quantitative Aptitude',
    topic: 'Number Series',
    difficulty: 'Hard',
    examCategory: ['SSC', 'Banking'],
    isPYQ: true,
    pyqYear: 2023,
    isBookmarked: false,
    tags: ['series', 'number'],
  },
];

export const mockExams: Exam[] = [
  {
    id: 'e1',
    title: 'SSC CGL Tier 1 — Full Mock Test 1',
    category: 'SSC',
    totalQuestions: 100,
    durationMinutes: 60,
    negativeMarking: 0.5,
    type: 'mock',
    isFree: true,
    attemptedCount: 15420,
    averageScore: 62.4,
    sections: [
      { name: 'General Intelligence & Reasoning', subject: 'Reasoning', questionCount: 25 },
      { name: 'General Awareness', subject: 'GA', questionCount: 25 },
      { name: 'Quantitative Aptitude', subject: 'Maths', questionCount: 25 },
      { name: 'English Comprehension', subject: 'English', questionCount: 25 },
    ],
  },
  {
    id: 'e2',
    title: 'IBPS PO Prelims — Mock Test 1',
    category: 'Banking',
    totalQuestions: 100,
    durationMinutes: 60,
    negativeMarking: 0.25,
    type: 'mock',
    isFree: true,
    attemptedCount: 12350,
    averageScore: 58.2,
    sections: [
      { name: 'English Language', subject: 'English', questionCount: 30 },
      { name: 'Quantitative Aptitude', subject: 'Maths', questionCount: 35 },
      { name: 'Reasoning Ability', subject: 'Reasoning', questionCount: 35 },
    ],
  },
  {
    id: 'e3',
    title: 'RRB NTPC — CBT 1 Mock Test',
    category: 'RRB',
    totalQuestions: 100,
    durationMinutes: 90,
    negativeMarking: 0.33,
    type: 'mock',
    isFree: false,
    attemptedCount: 8920,
    averageScore: 65.1,
    sections: [
      { name: 'Mathematics', subject: 'Maths', questionCount: 30 },
      { name: 'General Intelligence & Reasoning', subject: 'Reasoning', questionCount: 30 },
      { name: 'General Awareness', subject: 'GA', questionCount: 40 },
    ],
  },
  {
    id: 'e4',
    title: 'Daily Quiz — Quantitative Aptitude',
    category: 'SSC',
    totalQuestions: 10,
    durationMinutes: 12,
    negativeMarking: 0,
    type: 'daily_quiz',
    isFree: true,
    attemptedCount: 8200,
    averageScore: 72,
    sections: [{ name: 'Quant', subject: 'Maths', questionCount: 10 }],
  },
  {
    id: 'e5',
    title: 'Reasoning Sectional — Blood Relations',
    category: 'SSC',
    totalQuestions: 25,
    durationMinutes: 20,
    negativeMarking: 0,
    type: 'sectional',
    isFree: true,
    attemptedCount: 5600,
    averageScore: 68,
    sections: [{ name: 'Blood Relations', subject: 'Reasoning', questionCount: 25 }],
  },
];

export const mockTestResult: TestResult = {
  id: 'r1',
  examId: 'e1',
  examTitle: 'SSC CGL Tier 1 — Full Mock Test 1',
  score: 148.5,
  maxScore: 200,
  totalQuestions: 100,
  attempted: 92,
  correct: 68,
  incorrect: 24,
  skipped: 8,
  accuracy: 73.9,
  timeTaken: 3245,
  rank: 342,
  percentile: 88.5,
  submittedAt: new Date().toISOString(),
  sectionWise: [
    { name: 'General Intelligence & Reasoning', correct: 18, incorrect: 6, skipped: 1, score: 33, maxScore: 50, accuracy: 75 },
    { name: 'General Awareness', correct: 21, incorrect: 3, skipped: 1, score: 40.5, maxScore: 50, accuracy: 87.5 },
    { name: 'Quantitative Aptitude', correct: 15, incorrect: 9, skipped: 1, score: 25.5, maxScore: 50, accuracy: 62.5 },
    { name: 'English Comprehension', correct: 14, incorrect: 6, skipped: 5, score: 49.5, maxScore: 50, accuracy: 70 },
  ],
  topicWise: [
    { topic: 'Number Series', subject: 'Maths', correct: 4, total: 5, accuracy: 80 },
    { topic: 'Blood Relations', subject: 'Reasoning', correct: 3, total: 4, accuracy: 75 },
    { topic: 'Indian Polity', subject: 'GA', correct: 5, total: 5, accuracy: 100 },
    { topic: 'Reading Comprehension', subject: 'English', correct: 6, total: 8, accuracy: 75 },
    { topic: 'Percentage', subject: 'Maths', correct: 2, total: 5, accuracy: 40 },
    { topic: 'Coding-Decoding', subject: 'Reasoning', correct: 4, total: 5, accuracy: 80 },
    { topic: 'History & Culture', subject: 'GA', correct: 4, total: 5, accuracy: 80 },
    { topic: 'Speed & Distance', subject: 'Maths', correct: 2, total: 5, accuracy: 40 },
  ],
};

export const mockPerformanceData: PerformanceData[] = [
  { date: 'Mar 25', accuracy: 65, questionsAttempted: 40, studyTime: 90, xpEarned: 150 },
  { date: 'Mar 26', accuracy: 70, questionsAttempted: 55, studyTime: 110, xpEarned: 200 },
  { date: 'Mar 27', accuracy: 68, questionsAttempted: 30, studyTime: 60, xpEarned: 100 },
  { date: 'Mar 28', accuracy: 74, questionsAttempted: 70, studyTime: 130, xpEarned: 250 },
  { date: 'Mar 29', accuracy: 72, questionsAttempted: 50, studyTime: 100, xpEarned: 180 },
  { date: 'Mar 30', accuracy: 78, questionsAttempted: 65, studyTime: 120, xpEarned: 220 },
  { date: 'Mar 31', accuracy: 74, questionsAttempted: 45, studyTime: 95, xpEarned: 160 },
];

export const mockHeatmapData: TopicHeatmapData[] = [
  { subject: 'Maths', topic: 'Number Series', accuracy: 82, questionsAttempted: 45, status: 'strong' },
  { subject: 'Maths', topic: 'Percentage', accuracy: 45, questionsAttempted: 30, status: 'weak' },
  { subject: 'Maths', topic: 'Speed & Distance', accuracy: 58, questionsAttempted: 25, status: 'moderate' },
  { subject: 'Maths', topic: 'Profit & Loss', accuracy: 75, questionsAttempted: 40, status: 'strong' },
  { subject: 'Maths', topic: 'Simplification', accuracy: 38, questionsAttempted: 20, status: 'weak' },
  { subject: 'Reasoning', topic: 'Blood Relations', accuracy: 78, questionsAttempted: 35, status: 'strong' },
  { subject: 'Reasoning', topic: 'Coding-Decoding', accuracy: 85, questionsAttempted: 50, status: 'strong' },
  { subject: 'Reasoning', topic: 'Direction Sense', accuracy: 55, questionsAttempted: 18, status: 'moderate' },
  { subject: 'Reasoning', topic: 'Syllogisms', accuracy: 42, questionsAttempted: 22, status: 'weak' },
  { subject: 'GA', topic: 'Indian Polity', accuracy: 90, questionsAttempted: 60, status: 'strong' },
  { subject: 'GA', topic: 'History & Culture', accuracy: 72, questionsAttempted: 45, status: 'strong' },
  { subject: 'GA', topic: 'Economy', accuracy: 50, questionsAttempted: 28, status: 'moderate' },
  { subject: 'GA', topic: 'Current Affairs', accuracy: 65, questionsAttempted: 80, status: 'moderate' },
  { subject: 'English', topic: 'Reading Comprehension', accuracy: 78, questionsAttempted: 55, status: 'strong' },
  { subject: 'English', topic: 'Error Detection', accuracy: 48, questionsAttempted: 30, status: 'weak' },
  { subject: 'English', topic: 'Fill in the Blanks', accuracy: 70, questionsAttempted: 40, status: 'moderate' },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: 'u100', name: 'Priya Patel', xp: 12450, examCategory: 'SSC' },
  { rank: 2, userId: 'u101', name: 'Amit Kumar', xp: 11890, examCategory: 'Banking' },
  { rank: 3, userId: 'u102', name: 'Sneha Gupta', xp: 11230, examCategory: 'SSC' },
  { rank: 4, userId: 'u103', name: 'Rohit Singh', xp: 10980, examCategory: 'RRB' },
  { rank: 5, userId: 'u104', name: 'Anita Sharma', xp: 10540, examCategory: 'Banking' },
  { rank: 342, userId: 'u1', name: 'Rahul Sharma', xp: 4250, examCategory: 'SSC' },
];

export const mockDiscussions: DiscussionThread[] = [
  {
    id: 'd1',
    title: 'How to solve profit & loss questions in under 30 seconds?',
    body: 'I keep making mistakes in P&L. Share your shortcuts.',
    authorId: 'u5',
    authorName: 'Priya Mehta',
    upvotes: 142,
    replyCount: 38,
    createdAt: '2024-03-28T10:00:00Z',
    subject: 'Maths',
    tags: ['profit-loss', 'shortcuts', 'maths'],
  },
  {
    id: 'd2',
    title: 'SSC CGL 2024 Tier 1 analysis and expected cutoff',
    body: 'Sharing my analysis after attempting today\'s exam. Paper was moderate.',
    authorId: 'u6',
    authorName: 'Amit Verma',
    upvotes: 284,
    replyCount: 75,
    createdAt: '2024-03-29T14:30:00Z',
    subject: 'GA',
    tags: ['ssc-cgl', 'cutoff', '2024'],
  },
  {
    id: 'd3',
    title: 'Best strategy for RRB NTPC GK section',
    body: 'Which topics should I focus on with only 2 months left?',
    authorId: 'u7',
    authorName: 'Rahul Yadav',
    upvotes: 98,
    replyCount: 22,
    createdAt: '2024-03-30T08:00:00Z',
    subject: 'GA',
    tags: ['rrb', 'gk', 'strategy'],
  },
];

export const mockStudyRooms: StudyRoom[] = [
  {
    id: 'sr1',
    name: 'SSC CGL Aspirants 2024',
    hostName: 'Priya M.',
    participantCount: 24,
    maxParticipants: 50,
    subject: 'General Awareness',
    isLive: true,
    inviteLink: '#',
  },
  {
    id: 'sr2',
    name: 'Banking PO — Quant Marathon',
    hostName: 'Raj K.',
    participantCount: 18,
    maxParticipants: 30,
    subject: 'Quantitative Aptitude',
    isLive: true,
    inviteLink: '#',
  },
];

export const mockDailyTasks: DailyTask[] = [
  { id: 't1', type: 'practice', title: 'Solve 20 Number Series questions', subject: 'Maths', topic: 'Number Series', estimatedMinutes: 25, xpReward: 80, isCompleted: true },
  { id: 't2', type: 'revision', title: 'Revise Indian Polity concepts', subject: 'GA', topic: 'Indian Polity', estimatedMinutes: 20, xpReward: 60, isCompleted: true },
  { id: 't3', type: 'mock', title: 'Take Daily Quiz', estimatedMinutes: 12, xpReward: 100, isCompleted: false },
  { id: 't4', type: 'practice', title: 'Practice Percentage problems', subject: 'Maths', topic: 'Percentage', estimatedMinutes: 30, xpReward: 90, isCompleted: false },
  { id: 't5', type: 'video', title: 'Watch: Simplification Tricks', subject: 'Maths', estimatedMinutes: 15, xpReward: 50, isCompleted: false },
];

export const mockBadges: Badge[] = [
  { id: 'b1', name: 'First Streak', description: 'Study 7 days in a row', icon: '🔥', type: 'streak', unlockedAt: '2024-02-01' },
  { id: 'b2', name: 'Accuracy King', description: 'Score 90%+ in any test', icon: '🎯', type: 'accuracy', unlockedAt: '2024-02-15' },
  { id: 'b3', name: 'Speed Demon', description: 'Average < 30s per question', icon: '⚡', type: 'speed', unlockedAt: '2024-03-01' },
  { id: 'b4', name: 'Centurion', description: 'Solve 100 questions in a day', icon: '💯', type: 'milestone', unlockedAt: '2024-03-10' },
  { id: 'b5', name: 'Social Butterfly', description: 'Join 5 study rooms', icon: '👥', type: 'social' },
  { id: 'b6', name: '30-Day Warrior', description: 'Study 30 days consecutively', icon: '🏆', type: 'streak' },
];
